
[ClassVersion("1.0.0.0"), FriendlyName("SPInstallAppFabricUpdate")]
class MSFT_SPInstallAppFabricUpdate : OMI_BaseResource
{
    [Key, Description("Build number of the cumulative update used to check if already installed")] String Build;
    [Required, Description("Path where CU binaries are located")] String BinaryDir;
    [Required, Description("Name of the CU executable to launch")] String CuExeName;
};

