[ClassVersion("1.0.0.0"), FriendlyName("SPSearchServiceApp")]
class MSFT_SPSearchServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the search service application")] string Name;
    [Write, Description("The proxy name, if not specified will be /Name of service app/ Proxy")] string ProxyName;
    [Required, Description("The application pool that it should run in")] string ApplicationPool;
    [Write, Description("The URL of the enterprise search center site collection")] string SearchCenterUrl;
    [Write, Description("The name of the database (noting that some search databases will use this as a prefix)")] string DatabaseName;
    [Write, Description("The server that host the databases for this service application")] string DatabaseServer;
    [Write, Description("Should SQL Server authentication be used to connect to the database?")] Boolean UseSQLAuthentication;
    [Write, Description("If using SQL authentication, the SQL credentials to use to connect to the instance"), EmbeddedInstance("MSFT_Credential")] String DatabaseCredentials;
    [Write, Description("The default content access account for this search service app"), EmbeddedInstance("MSFT_Credential")] String DefaultContentAccessAccount;
    [Write, Description("Should this search service application be a cloud based service app")] boolean CloudIndex;
    [Write, Description("Should alerts be enabled for this search service application")] boolean AlertsEnabled;
    [Write, Description("Should the permissions for the Farm account on the Search databases be corrected")] boolean FixFarmAccountPermissions;
    [Write, Description("Present if the service app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Specifies the number of consecutive crawls where Access Denied or File Not Found errors were encountered before the item is deleted from the index")] uint16 ErrorDeleteCountAllowed;
    [Write, Description("Specifies the number of hours since the first Access Denied or File Not Found errors were encountered in a crawl before the item is deleted from the index")] uint16 ErrorDeleteIntervalAllowed;
    [Write, Description("Specifies the number of consecutive crawls where other errors were encountered before the item is deleted from the index")] uint16 ErrorCountAllowed;
    [Write, Description("Specifies the number of hours since the first other errors were encountered in a crawl before the item is deleted from the index")] uint16 ErrorIntervalAllowed;
    [Write, Description("Specifies what items get deleted: 0 - All unvisited items, 1 - (Default) All unvisited items that have the same host as the start address, 2 - None of the unvisited items. You can specify the following three values:")] uint16 DeleteUnvisitedMethod;
    [Write, Description("Specifies the number of consecutive crawls in which errors were encountered while fetching changes from the SharePoint content database")] uint16 RecrawlErrorCount;
    [Write, Description("Specifies the number of hours since the first error were encountered while fetching changes from the SharePoint content database")] uint16 RecrawlErrorInterval;
};
