/*
**Description**

Creates a managed metadata service application.
The application pool property specifies which application pool it should use, and will reset the application back to this pool if it is changed after its initial provisioning.
The database server and database name properties are only used during provisioning, and will not be altered as part of the ongoing operation of the DSC resource. 

**Example**

    xSPManagedMetaDataServiceApp ManagedMetadataServiceApp
    {  
        Name              = "Managed Metadata Service Application"
        InstallAccount    = $InstallAccount
        ApplicationPool   = "SharePoint Service Applications"
        DatabaseServer    = $DatabaseServer
        DatabaseName      = "SP_ManagedMetadata"
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPManagedMetaDataServiceApp")]
class MSFT_xSPManagedMetaDataServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the managed metadata service application")] string Name;
    [Required, Description("The application pool that the service app will use")] string ApplicationPool;
    [Write, Description("The name of the database server which will host the application")] string DatabaseServer;
    [Write, Description("The name of the database for the service application")] string DatabaseName;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
