/*
**Description**

Creates a managed metadata service application.
The application pool property specifies which application pool it should use, and will reset the application back to this pool if it is changed after its initial provisioning.
The database server and database name properties are only used during provisioning, and will not be altered as part of the ongoing operation of the DSC resource. 

**Example**

    xSPManagedMetaDataServiceApp ManagedMetadataServiceApp
    {  
        Name              = "Managed Metadata Service Application"
        InstallAccount    = $InstallAccount
        ApplicationPool   = "SharePoint Service Applications"
        DatabaseServer    = $DatabaseServer
        DatabaseName      = "SP_ManagedMetadata"
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPManagedMetaDataServiceApp")]
class MSFT_xSPManagedMetaDataServiceApp : OMI_BaseResource
{
    [Key] string Name;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Required] string ApplicationPool;
    [Write] string DatabaseServer;
    [Write] string DatabaseName;
};
