/*
**Description**

This resource is responsible for controlling the Site Use and Deletion settings on a specific web application.
You can enable or disable the Site Use and Deletion feature, specify the amount of days after which the alerts are being send, if sites have to be deleted automatically and if so after how many days this has to be done.

**Example**

    xSPWebAppSiteUseAndDeletion ConfigureSiteUseAndDeletion
    {
        Url                                      = "http://example.contoso.local"
        SendUnusedSiteCollectionNotifications    = $true
        UnusedSiteNotificationPeriod             = 90
        AutomaticallyDeleteUnusedSiteCollections = $true
        UnusedSiteNotificationsBeforeDeletion    = 24
        PsDscRunAsCredential                     = $InstallAccount
    }
*/

[ClassVersion("1.0.0"), FriendlyName("xSPWebAppSiteUseAndDeletion")]
Class MSFT_xSPWebAppSiteUseAndDeletion : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string Url;
    [Write, Description("Should emails be sent to notify site owners of unused site collections")] boolean SendUnusedSiteCollectionNotifications;
    [Write, Description("How many days should pass before a site is flagged as unused")] uint32 UnusedSiteNotificationPeriod;
    [Write, Description("Should unused site collection be automatically deleted")] boolean AutomaticallyDeleteUnusedSiteCollections;
    [Write, Description("How many days before an unused site is deleted should an email be sent to the owner")] uint32 UnusedSiteNotificationsBeforeDeletion;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};
