/*
**Description**

This resource will set the value for the app domain settings at the farm level.
You can set the domain name and the prefix that is to be used for app URLs.


**Example**

    xSPAppDomain LocalFarmAppUrls
    {
        AppDomain = "contosointranetapps.com"
        Prefix = "app"
        PsDscRunAsCredential = $InstallAccount
    }

*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPAppDomain")]
class MSFT_xSPAppDomain : OMI_BaseResource
{
    [Key, Description("The domain name for apps to use in this farm")] string AppDomain;
    [Required, Description("The prefix to go on to app URLs")] string Prefix;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    
};
