/*
**Description**

This resource is used to provision and manage an instance of the Work Management Services Service Application.
It will identify an instance of the work management service application through the application display name.
Currently the resource will provision the app if it does not yet exist, and will change the application pool associated to the app if it does not match the configuration.


Remarks
- Parameters MinimumTimeBetweenEwsSyncSubscriptionSearches, MinimumTimeBetweenProviderRefreshes, MinimumTimeBetweenSearchQueries are in Minutes



**Example**

   xSPWorkManagementServiceApp WorkManagementServiceApp
    {
        Name = "App Management Service Application"
        ApplicationPool = "SharePoint web services"
        MinimumTimeBetweenEwsSyncSubscriptionSearches = 10 
}
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPWorkManagementServiceApp")]
class MSFT_xSPWorkManagementServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the work management service application")] string Name;
    [write, Description("Present to ensure the app exists, absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [write, Description("The name of the application pool this will run in")] String ApplicationPool;
    [Write, Description("The minimum amount of time bween EWS sync subscription searches")] uint32 MinimumTimeBetweenEwsSyncSubscriptionSearches;
    [Write, Description("The minimum time between provider refreshes")] uint32 MinimumTimeBetweenProviderRefreshes;
    [Write, Description("The minimum time between search queries")] uint32 MinimumTimeBetweenSearchQueries;
    [Write, Description("The number of subscription syncronisations per EWS sync run")] uint32 NumberOfSubscriptionSyncsPerEwsSyncRun;
    [Write, Description("How many users will EWS calls include at once")] uint32 NumberOfUsersEwsSyncWillProcessAtOnce;
    [Write, Description("How many users are included in a batch for EWS")] uint32 NumberOfUsersPerEwsSyncBatch;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
