/*
**Description**

This resource is used to provision and manage an instance of the Work Management Services Service Application.
It will identify an instance of the work management service application through the application display name.
Currently the resource will provision the app if it does not yet exist, and will change the application pool associated to the app if it does not match the configuration.


Remarks
- Parameters MinimumTimeBetweenEwsSyncSubscriptionSearches, MinimumTimeBetweenProviderRefreshes, MinimumTimeBetweenSearchQueries are in Minutes



**Example**

   xSPWorkManagementServiceApp WorkManagementServiceApp
    {
        Name = "App Management Service Application"
        AppPool = "SharePoint web services"
        MinimumTimeBetweenEwsSyncSubscriptionSearches = 10 
}
*/
[ClassVersion("1.0.0.0"), FriendlyName("WorkManagementServiceApp")]
class MSFT_WorkManagementServiceApp : OMI_BaseResource
{
    [Key] string Name;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write] String ApplicationPool;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Write] System.UInt32 MinimumTimeBetweenEwsSyncSubscriptionSearches;
    [Write] System.UInt32 MinimumTimeBetweenProviderRefreshes;
    [Write] System.UInt32 MinimumTimeBetweenSearchQueries;
    [Write] System.UInt32 NumberOfSubscriptionSyncsPerEwsSyncRun;
    [Write] System.UInt32 NumberOfUsersEwsSyncWillProcessAtOnce;
    [Write] System.UInt32 NumberOfUsersPerEwsSyncBatch;
};

