/*
**Description**

This resource provisions an instance of the state service in to the local farm.
The database specific parameters are only used during initial provisioning of the app, and will not change database settings beyond the initial deployment.

**Example**

    xSPStateServiceApp StateServiceApp
    {
        Name                 = "State Service Application"
        DatabaseName         = "SP_State"
        PsDscRunAsCredential = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPStateServiceApp")]
class MSFT_xSPStateServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the state service app")] string Name;
    [Write, Description("The database credentials for accessing the database"), EmbeddedInstance("MSFT_Credential")] String DatabaseCredentials;
    [Required, Description("The name of the database for the service app")] string DatabaseName;
    [Write, Description("The name of the database server")] string DatabaseServer;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
