[ClassVersion("1.0.0"), FriendlyName("xSPBlockedFileTypes")]
Class MSFT_xSPBlockedFileTypes
{
    [Key] string Url;
    [write] string Blocked[];
    [write] string EnsureBlocked[];
    [write] string EnsureAllowed[];
    [Write, EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};