/*
**Description**

This resource will configure the App Domain at a specific zone for the given Web Application.
The configuration is done per zone on the specified web application, allowing for the setting of unique app domains for each extension of a web application.
The app prefix should still be set using the xSPAppDomain resource before this is applied to customise a specific zone. 

 
**Example**

    xSPWebApplicationAppDomain Domain
    {
        AppDomain = "contosointranetapps.com"
        WebApplication ="http://portal.contoso.com";
        Zone = "Default";
        Port = 80;
        SSL = $false;
        PsDscRunAsCredential = $InstallAccount
    }

*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPWebApplicationAppDomain")]
class MSFT_xSPWebApplicationAppDomain : OMI_BaseResource
{
    [Key, Description("The URL of the web application to set the app domain for")] string WebApplication;
    [Key, Description("The zone that this app domain applies to"), ValueMap{"Default","Internet","Intranet","Extranet","Custom"}, Values{"Default","Internet","Intranet","Extranet","Custom"}] string Zone;
    [Required, Description("The domain for apps in this web app zone")] string AppDomain;
    [Write, Description("The port to run apps on")] string Port;
    [Write, Description("Should apps run under SSL")] boolean SSL;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
