/*
**Description**

This resource is responsible for creating Visio Graphics Service Application instances within the local SharePoint farm.
The resource will provision and configure the Visio Graphics Service Application.
**Example**
    xSPVisioServiceApp VisioServices
    {
        Name = "Visio Graphics Service Application"
        ApplicationPool = "SharePoint Web Services"
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPVisioServiceApp")]
class MSFT_xSPVisioServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the service application")] string Name;
    [Required, Description("The name of the application pool to run the service app in")] string ApplicationPool;
};
