#
# Module manifest for module 'SharePointDsc.Util'
#
# Generated by: DSC Community
#
# Generated on: 3-2-2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'SharePointDsc.Util.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # ID used to uniquely identify this module
    GUID              = 'f6a011ea-5e00-4927-a0f9-a12d234b2c02'

    # Author of this module
    Author            = 'DSC Community'

    # Company or vendor of this module
    CompanyName       = 'DSC Community'

    # Copyright statement for this module
    Copyright         = 'Copyright the DSC Community contributors. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Functions used by the DSC resources in SharePointDsc.'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Add-SPDscEvent',
        'Add-SPDscUserToLocalAdmin',
        'Clear-SPDscKerberosToken',
        'Compare-PSCustomObjectArrays',
        'Convert-SPDscADGroupIDToName',
        'Convert-SPDscADGroupNameToID',
        'Convert-SPDscArrayToString',
        'Convert-SPDscCIMInstanceToString',
        'Convert-SPDscHashtableToString',
        'ConvertTo-ReverseString',
        'ConvertTo-TwoDigitFlipString',
        'Export-SPConfiguration',
        'Export-SPDscDiagnosticData',
        'Format-OfficePatchGUID',
        'Get-SPDscAssemblyVersion',
        'Get-SPDscBuildVersion',
        'Get-SPDscContentService',
        'Get-SPDscFarmAccount',
        'Get-SPDscFarmAccountName',
        'Get-SPDscFarmProductsInfo',
        'Get-SPDscFarmVersionInfo',
        'Get-SPDscInstalledProductVersion',
        'Get-SPDscOSVersion',
        'Get-SPDscRegistryKey',
        'Get-SPDscRegProductsInfo',
        'Get-SPDscServerPatchStatus',
        'Get-SPDscServiceContext',
        'Get-SPDscUserProfileSubTypeManager',
        'Invoke-SPDscCommand',
        'Remove-SPDscGenericObject',
        'Remove-SPDscUserToLocalAdmin',
        'Remove-SPDscZoneMap',
        'Rename-SPDscParamValue',
        'Resolve-SPDscSecurityIdentifier',
        'Set-SPDscObjectPropertyIfValuePresent',
        'Set-SPDscZoneMap',
        'Test-SPDscIsADUser',
        'Test-SPDscObjectHasProperty',
        'Test-SPDscParameterState',
        'Test-SPDscRunningAsFarmAccount',
        'Test-SPDscUserIsLocalAdmin'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @('Start-SharePointDSCExtract')

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
