/*
**Description**

This resource is used to configure quota templates in the farm.
These settings will be used to make sure a certain quota template exists or not. When it exists, it will also make sure the settings are configured as specified.

**Example**

    xSPQuotaTemplate TeamsiteTemplate
    {
        Name = "Teamsite"
        StorageMaxInMB = 1024
        StorageWarningInMB = 512
        MaximumUsagePointsSolutions = 1000
        WarningUsagePointsSolutions = 800
        Ensure = "Present"
    }
*/

[ClassVersion("1.0.0.0"), FriendlyName("xSPQuotaTemplate")]
class MSFT_xSPQuotaTemplate : OMI_BaseResource
{
    [Key, Description("The name of the quota template")] string Name;
    [Write, Description("The maximum storage for sites of this template in MB")] uint32 StorageMaxInMB;
    [Write, Description("The amount of storage for sites of this template that triggers a warning")] uint32 StorageWarningInMB;
    [Write, Description("The maximum number of performance points for sandbox solutions for this template")] uint32 MaximumUsagePointsSolutions;
    [Write, Description("The warning number of performance points for sandbox solutions for this template")] uint32 WarningUsagePointsSolutions;
    [Required, Description("Present to create this template, absent to ensure it does not exist"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
