/*
**Description**

This resource is used to set the outgoing email settings for either a single web application, or the whole farm. 
To configure the resource for a specific web app, use the URL of the web application for the WebAppUrl property, to change the settings for the whole farm use the URL of the central admin website instead.
It is possible to set the outgoing server, from address, reply to address and the character set to be used for emails.

**Example**

    xSPOutgoingEmailSettings FarmWideEmailSettings
    {  
        WebAppUrl             = "http://sharepoint1:2013"
        SMTPServer            = "smtp.contoso.com"
        FromAddress           = "sharepoint@contoso.com"
        ReplyToAddress        = "noreply@contoso.com"
        PsDscRunAsCredential  = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPOutgoingEmailSettings")]
class MSFT_xSPOutgoingEmailSettings : OMI_BaseResource
{
    [key, Description("The URL of the web application. If you want to set the global settings use the Central Admin URL")] string WebAppUrl;
    [Required, Description("The SMTP server for outgoing mail")] string SMTPServer;
    [Required, Description("The from address to put on messages")] string FromAddress;
    [Required, Description("The email address that replies should be directed to")] string ReplyToAddress;
    [Required, Description("The character set to use on messages")] string CharacterSet;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

