/*
**Description**

This resource is used to set the global antivirus settings for the local farm.
These settings will be used to control the behavior of an external anti-virus scanning tool that is able to integrate with SharePoint.
Note that this will not scan documents for viruses on it's own, an external tool still needs to be installed on the servers that integrates with SharePoint.

**Example**

    xSPAntivirusSettings AVSettings
    {
        ScanOnDownload        = $true
        ScanOnUpload          = $true
        AllowDownloadInfected = $false
        AttemptToClean        = $false
    }
*/

[ClassVersion("1.0.0.0"), FriendlyName("xSPAntivirusSettings")]
class MSFT_xSPAntivirusSettings : OMI_BaseResource
{
    [Key, Description("Should documents be scanned before being downloaded")] Boolean ScanOnDownload;
    [Write, Description("Should documents be scanned on upload")] Boolean ScanOnUpload;
    [Write, Description("Should documents that are infected be allowed to be downloaded")] Boolean AllowDownloadInfected;
    [Write, Description("Should infected documents be handed to the AV engine to attempt cleaning")] Boolean AttemptToClean;
    [Write, Description("What is the timeout for an AV scan in seconds")] Uint16 TimeoutDuration;
    [Write, Description("How many concurrent threads should the AV engine be able to run on a server")] Uint16 NumberOfThreads;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

