/*
**Description**

This resource will configure the App Catalog settings for Web Applications and Host Named Site Collections(HNSC).
The catalog site needs to have been created using the correct template. 
The catalog URL for HNSC works based on convention. All HNSC need to have catalog on the same path.

**Example**

    xSPAppCatalog MainAppCatalog
    {
        WebApp = "https://content.sharepoint.contoso.com"
        AppCatalogUrl = "/sites/AppCatalog"
    }

*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPAppCatalog")]
class MSFT_xSPAppCatalog : OMI_BaseResource
{
    [Key] string WebApp;
    [Required] string AppCatalogUrl;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    
};
