/*
**Description**

This resource will ensure that a specific site collection is marked as the app catalog for the web application that the site is in.
The catalog site needs to have been created using the correct template (APPCATALOG#0).

**Example**

    xSPAppCatalog MainAppCatalog
    {
        SiteUrl = "https://content.sharepoint.contoso.com/sites/AppCatalog"
        PsDscRunAsCredential = $SPSetupAccount
    }

*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPAppCatalog")]
class MSFT_xSPAppCatalog : OMI_BaseResource
{
    [Key, Description("The URL of the site collection that will be the app catalog for the web app that it is in")] string SiteUrl;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
