/*
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPSearchRoles")]
class MSFT_xSPSearchRoles : OMI_BaseResource
{
    [Key] String ServiceAppName;
    [Required] Boolean Admin;
    [Required] Boolean Crawler;
    [Required] Boolean ContentProcessing;
    [Required] Boolean AnalyticsProcessing;
    [Required] Boolean QueryProcessing;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Required, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Uint32 FirstPartitionIndex;
    [Write] String FirstPartitionDirectory;
    [Write] String FirstPartitionServers;
};