/*
**Description**

This resource is responsible for provisioning a search topology in to the current farm.
It allows the configuration to dictate the search topology roles that the current server should be running.
Any combination of roles can be specified and the topology will be upaded to reflect the current servers new roles.
If this is the first server to apply topology to a farm, then at least one search index must be provided. 
To this end, the FirstPartitionIndex, FirstPartitionDirectory and FirstPartitionServers allow configuring where the first index partition will belong.
This will behave the same as the xSPSearchIndexPartition resource.  

**Example**

    xSPSearchRoles LocalSearchRoles
    {
        Ensure                  = "Present"
        Admin                   = $true
        Crawler                 = $true
        ContentProcessing       = $true
        AnalyticsProcessing     = $true
        QueryProcessing         = $true
        ServiceAppName          = "Search Service Application"
        PsDscRunAsCredential    = $SPSetupAccount
        FirstPartitionIndex     = 0
        FirstPartitionDirectory = "I:\SearchIndexes\0"
		FirstPartitionServers   = "Server1,Server2"
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPSearchRoles")]
class MSFT_xSPSearchRoles : OMI_BaseResource
{
    [Key] String ServiceAppName;
    [Required] Boolean Admin;
    [Required] Boolean Crawler;
    [Required] Boolean ContentProcessing;
    [Required] Boolean AnalyticsProcessing;
    [Required] Boolean QueryProcessing;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Required, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Uint32 FirstPartitionIndex;
    [Write] String FirstPartitionDirectory;
    [Write] String FirstPartitionServers;
};