/*
**Description**

This resource will provision a state service app to the local farm. 
Specify the name of the database server and database name to provision the app with, and optionally include the session timeout value.
If session timeout is not provided it will default to 60.

**Example**

    xSPSessionStateService StateServiceApp
    {
        DatabaseName         = "SP_StateService"
        DatabaseServer       = "SQL.test.domain"
        Enabled              = $true
        PsDscRunAsCredential = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPSessionStateService")]
class MSFT_xSPSessionStateService : OMI_BaseResource
{
    [Key, Description("The name of the database for the service")] string DatabaseName;
    [Key, Description("The name of the database server for the database")] string DatabaseServer;
    [Required, Description("Is the state service enabled")] boolean Enabled;
    [Write, Description("What is the timeout on sessions")] uint32 SessionTimeout;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

