/*
**Description**

This resource is used for provisioning an application pool that can be used for service applications. 
The account used for the service account must already be registered as a managed account (which can be provisioned through [xSPManagedAccount](xSPManagedAccount)).

**Example**

    xSPServiceAppPool MainServiceAppPool
    {
        Name           = "SharePoint Service Applications"
        ServiceAccount = "Demo\ServiceAccount"
        InstallAccount = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPServiceAppPool")]
class MSFT_xSPServiceAppPool : OMI_BaseResource
{
    [Key, Description("The name of application pool")] string Name;
    [Required, Description("The name of the managed account to run this service account as")] string ServiceAccount;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

