/*
**Description**

This resource is used for provisioning an application pool that can be used for service applications. 
The account used for the service account must already be registered as a managed account (which can be provisioned through [xSPManagedAccount](xSPManagedAccount)).

**Example**

    xSPServiceAppPool MainServiceAppPool
    {
        Name           = "SharePoint Service Applications"
        ServiceAccount = "Demo\ServiceAccount"
        InstallAccount = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPServiceAppPool")]
class MSFT_xSPServiceAppPool : OMI_BaseResource
{
    [Key] string Name;
    [Required] string ServiceAccount;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

