/*
**Description**

This resource is responsible for creating Access Services Application instances within the local SharePoint farm.
The resource will provision and configure the Access Services Service Application.
**Example**
    xSPAccessServiceApp AccessServices
    {
        Name = "Access Services Service Application"
        ApplicationPool = "SharePoint Web Services"
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPAccessServiceApp")]
class MSFT_xSPAccessServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the service application")] string Name;
    [Required, Description("The name of the application pool to run the service app in")] string ApplicationPool;
    [Required, Description("The name of the database server to be used")] string DatabaseServer ;
};
