/*
**Description**

This resource will be responsible for joining a server to an existing SharePoint farm.
To create a new farm use the [xSPCreateFarm](xSPCreateFarm) resource on a different server to begin with, and then pass the same database server and configuration database name parameters to the additional servers using this resource.
After the server has joined the farm, the process will wait for 5 minutes to allow farm specific configuration to take place on the server, before allowing further DSC configuration to take place.

**Example**

    xSPJoinFarm JoinSPFarm
    {
        DatabaseServer           = $DatabaseServer
        FarmConfigDatabaseName   = "SP_Config"
        Passphrase               = $FarmPassPhrase
        PsDscRunAsCredential     = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPJoinFarm")]
class MSFT_xSPJoinFarm : OMI_BaseResource
{
    [Key, Description("The name of the config database to connect to")] string FarmConfigDatabaseName;
    [Key, Description("The server that hosts the config database")] string DatabaseServer;
    [Required, Description("The passphrase that should be used to join the farm")] string Passphrase;
    [Write, Description("SharePoint 2016 only - the MinRole role to enroll this server as"), ValueMap{"Application","Custom","DistributedCache","Search","SingleServer","SingleServerFarm","SpecialLoad","WebFrontEnd"}, Values{"Application","Custom","DistributedCache","Search","SingleServer","SingleServerFarm","SpecialLoad","WebFrontEnd"}] string ServerRole;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
