/*
**Description**

This resource is responsible for creating a web application within the local SharePoint farm.
The resource will provision the web application with all of the current settings, and then ensure that it stays part of the correct application pool beyond that (additional checking and setting of properties will be added in future releases).

**Example**

    xSPWebApplication HostNameSiteCollectionWebApp
    {
        Name                   = "SharePoint Sites"
        ApplicationPool        = "SharePoint Sites"
        ApplicationPoolAccount = "CONTOSO\svcSPWebApp"
        AllowAnonymous         = $false
        AuthenticationMethod   = "NTLM"
        DatabaseName           = "SP_Content_01"
        DatabaseServer         = "SQL.contoso.local\SQLINSTANCE"
        Url                    = "http://example.contoso.local"
        Port                   = 80
        PsDscRunAsCredential   = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPWebApplication")]
class MSFT_xSPWebApplication : OMI_BaseResource
{
    [Key] string Name;
    [Required] string ApplicationPool;
    [Required] string ApplicationPoolAccount;
    [Required] string Url;
    [Write] boolean AllowAnonymous;
    [Write, ValueMap{"NTLM","Kerberos"}, Values{"NTLM","Kerberos"}] string AuthenticationMethod;
    [Write] string DatabaseName;
    [Write] string DatabaseServer;
    [Write] string HostHeader;
    [Write] string Path;
    [Write] string Port;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

