[ClassVersion("1.0.0")]
Class MSFT_xSPFilesTypes
{
    [write]String Blocked[];
    [write]String EnsureBlocked[];
    [write]String EnsureAllowed[];
};
[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationHappyHour
{
    [write] uint32 Hour;
    [write] uint32 Minute;
    [write] uint32 Duration;

};
[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationThrottling
{
    [write]uint32 ListViewThreshold;
    [write]boolean AllowObjectModelOverride; 
    [write]uint32 AdminThreshold;
    [write]uint32 ListViewLookupThreshold;
    [write]boolean HappyHourEnabled;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationHappyHour")] String HappyHour;
    [write]uint32 UniquePermissionThreshold;
    [write]boolean RequestThrottling;
    [write]boolean ChangeLogEnabled;
    [write]uint32 ChangeLogExpiryDays;
    [write]boolean EventHandlersEnabled;
    
};

[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationWorkflowSettings
{
    [write]boolean ExternalWorkflowParticipantsEnabled;
    [write]boolean UserDefinedWorkflowsEnabled;
    [write]boolean EmailToNoPermissionWorkflowParticipantsEnable;
};

[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationSettings
{
    [write]uint32 TimeZone;
    [write]String DefaultQuotaTemplate;
    [write]boolean Alerts;
    [write]uint32 AlertsLimit;
    [write]boolean RSS;
    [write]boolean BlogAPI;
    [write]boolean BlogAPIAuthenticated;
    [write, ValueMap{"Strict","Permissive"}, Values{"Stric","Permissive"}] String BrowserFileHandling;
    
    [write]boolean SecurityValidation;
    [write]boolean RecycleBinEnabled;
    [write]boolean SecondStageRecycleBinEnabled;
    [write]boolean RecycleBinCleanupEnabled ;
    [write]uint32 RecycleBinRetentionPeriod;
    [write]uint32 SecondStageRecycleBinQuota;
    [write]uint32 MaximumUploadSize;
    [write]boolean CustomerExperienceProgram;
    [write]boolean PresenceEnabled;
};

[ClassVersion("1.1.0.0"), FriendlyName("xSPWebApplication")]
class MSFT_xSPWebApplication : OMI_BaseResource
{
    [Key] string Name;
    [Required] string ApplicationPool;
    [Required] string ApplicationPoolAccount;
    [Required] string Url;
    [Write] boolean AllowAnonymous;
    [Write, ValueMap{"NTLM","Kerberos"}, Values{"NTLM","Kerberos"}] string AuthenticationMethod;
    [Write] string DatabaseName;
    [Write] string DatabaseServer;
    [Write] string HostHeader;
    [Write] string Path;
    [Write] string Port;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationSettings")] String GeneralSettings;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationWorkflowSettings")] String WorkflowSettings;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationThrottling")] String ThrottlingSettings;
    [Write, EmbeddedInstance("MSFT_xSPFilesTypes")] String BlockedFileTypes;
};

