/*
**Description**

This resource is responsible for creating Performance Point Service Application instances within the local SharePoint farm.
The resource will provision and configure the Performance Point Service Application.
**Example**
    xSPPerformancePointServiceApp PerformancePoint
    {
        Name = "Performance Point Service Application"
        ApplicationPool = "SharePoint Web Services"
        InstallAccount  = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPPerformancePointServiceApp")]
class MSFT_xSPPerformancePointServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the service application")] string Name;
    [Required, Description("The name of the application pool to run the service app in")] string ApplicationPool;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
