/*
**Description**

This resource is used to set the User Policies for web applications.
The usernames can be either specified in Classic or Claims format, both will be accepted.
There are a number of approaches to how this can be implemented.
The "Members" property will set a specific list of members for the group, making sure that every user/group in the list is in the group and all others that are members and who are not in this list will be removed.
The "MembersToInclude" and "MembersToExclude" properties will allow you to control a specific set of users to add or remove, without changing any other members that are in the group already that may not be specified here, allowing for some manual management outside of this configuration resource.

**Example**

    xSPWebAppPolicy WebAppPolicy
    {
        WebAppUrl            = "http://sharepoint.contoso.com"
        Members = @(
            @(MSFT_xSPWebPolicyPermissions {
                Username           = "contoso\user1"
                PermissionLevel    = "Full Control"
                ActAsSystemAccount = $true
            })
            @(MSFT_xSPWebPolicyPermissions {
                Username        = "contoso\user2"
                PermissionLevel = "Full Read"
            })
        )
        PsDscRunAsCredential = $InstallAccount
    }

    xSPWebAppPolicy WebAppPolicy
    {
        WebAppUrl            = "http://sharepoint.contoso.com"
        MembersToInclude = @(
            @(MSFT_xSPWebPolicyPermissions {
                Username        = "contoso\user1"
                PermissionLevel = "Full Control"
            })
            @(MSFT_xSPWebPolicyPermissions {
                Username        = "contoso\user2"
                PermissionLevel = "Full Read"
            })
        )
        MembersToExclude = @(
            @(MSFT_xSPWebPolicyPermissions {
                Username = "contoso\user3"
            })
        )
        PsDscRunAsCredential = $InstallAccount
    }

*/
[ClassVersion("1.0.0")]
Class MSFT_xSPWebPolicyPermissions
{
    [Key, Description("Name of the account")] String Username;
    [Required, Description("Permission level of the account"), ValueMap{"Deny All","Deny Write","Full Read","Full Control"}, Values{"Deny All","Deny Write","Full Read","Full Control"}] String PermissionLevel;
    [Write, Description("Specifies if the account is allowed to act as a system account")] Boolean ActAsSystemAccount;
};

[ClassVersion("1.0.0.0"), FriendlyName("xSPWebAppPolicy")]
class MSFT_xSPWebAppPolicy : OMI_BaseResource
{
    [Key], Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("Exact list of accounts that will have to get Web Policy permissions"), EmbeddedInstance("MSFT_xSPWebPolicyPermissions")] String Members[];
    [Write, Description("List of all accounts that must be in the Web Policy group"), EmbeddedInstance("MSFT_xSPWebPolicyPermissions")] String MembersToInclude[];
    [Write, Description("List of all accounts that are not allowed to have any Web Policy permissions"), EmbeddedInstance("MSFT_xSPWebPolicyPermissions")] String MembersToExclude[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

