/*
**Description**

This resource is used to set the "super user" and "super reader" cache accounts for the specified web application object (as described in the TechNet article [Configure object cache user accounts in SharePoint Server 2013](https://technet.microsoft.com/en-us/library/ff758656.aspx)).

**Example**

    xSPCacheAccounts SetCacheAccounts
    {
        WebAppUrl            = "http://sharepoint.contoso.com"
        SuperUserAlias       = "DEMO\svcSPSuperUser"
        SuperReaderAlias     = "DEMO\svcSPReader"
        PsDscRunAsCredential = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPWebAppPolicy")]
class MSFT_xSPWebAppPolicy : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Key, Description("The username for the policy")] string UserName;
    [Required, Description("The policy to apply"), ValueMap{"Deny All","Deny Write","Full Read","Full Control"}, Values{"Deny All","Deny Write","Full Read","Full Control"}] string PermissionLevel;
    [Write, Description("Should this user be treated as a system account")] boolean ActAsSystemUser;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

