/*
**Description**

This resource is responsible for provisioning and configuring the secure store service application. 
The parameters passed in (except those related to database specifics) are validated and set when the resource is run, the database values are only used in provisioning of the service application. 

**Example**

    xSPSecureStoreServiceApp SecureStoreServiceApp
    {
        Name            = "Secure Store Service Application"
        ApplicationPool = "SharePoint Service Applications"
        AuditingEnabled = $true
        AuditlogMaxSize = 30
        DatabaseName    = "SP_SecureStore"
        InstallAccount  = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPSecureStoreServiceApp")]
class MSFT_xSPSecureStoreServiceApp : OMI_BaseResource
{
    [Key] string Name;
    [Required] string ApplicationPool;
    [Required] boolean AuditingEnabled;
    [Write] uint32 AuditlogMaxSize;
    [Write, EmbeddedInstance("MSFT_Credential")] String DatabaseCredentials;
    [Write] string DatabaseName;
    [Write] string DatabaseServer;
    [Write, ValueMap {"Windows","SQL"}, Value{"Windows","SQL"}] string DatabaseAuthenticationType;
    [Write] string FailoverDatabaseServer;
    [Write] boolean PartitionMode;
    [Write] boolean Sharing;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

