/*
**Description**

This resource is used to specify if a specific service should be running (Ensure = "Present") or not running (Ensure = "Absent") on the current server. 
The name is the display name of the service as shown in the Central Admin website.

**Examples**

    xSPServiceInstance ManagedMetadataServiceInstance
    {  
        Name           = "Managed Metadata Web Service"
        Ensure         = "Present"
        InstallAccount = $InstallAccount
    }

    xSPServiceInstance StopBCSServiceInstance
    {  
        Name           = "Business Data Connectivity Service"
        Ensure         = "Absent"
        InstallAccount = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPServiceInstance")]
class MSFT_xSPServiceInstance : OMI_BaseResource
{
    [Key, Description("The name of the service instance to manage")] string Name;
    [Required, Description("Present to ensure it runs on this server, or absent to ensure it is stopped"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
