[ClassVersion("1.0.0.0"), FriendlyName("SPService")]
class MSFT_SPService : OMI_BaseResource
{
    [Key, Description("The name of the service instance to manage")] string Name;
    [Write, Description("Present to ensure the service runs in the farm, or absent to ensure it is stopped"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
};
