#
# Module manifest for module 'SharePointDsc'
#
# Generated by: Microsoft Corporation
#
# Generated on: 20/06/2018
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '3.0.0.0'

# ID used to uniquely identify this module
GUID = '6c1176a0-4fac-4134-8ca2-3fa8a21a7b90'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2015-2018 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This DSC module is used to deploy and configure SharePoint Server 2013, 2016 and 2019, and covers a wide range of areas including web apps, service apps and farm configuration.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @("modules\SharePointDsc.Util\SharePointDsc.Util.psm1")

# Functions to export from this module
#FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = @("Invoke-SPDSCCommand",
                    "Get-SPDSCInstalledProductVersion",
                    "Get-SPDSCContentService",
                    "Rename-SPDSCParamValue",
                    "Add-SPDSCUserToLocalAdmin",
                    "Remove-SPDSCUserToLocalAdmin",
                    "Test-SPDSCObjectHasProperty",
                    "Test-SPDSCRunAsCredential",
                    "Test-SPDSCUserIsLocalAdmin",
                    "Test-SPDscParameterState",
                    "Test-SPDSCIsADUser",
                    "Test-SPDSCRunningAsFarmAccount",
                    "Set-SPDscObjectPropertyIfValuePresent",
                    "Get-SPDSCUserProfileSubTypeManager",
                    "Get-SPDscOSVersion",
                    "Get-SPDSCRegistryKey",
                    "Resolve-SPDscSecurityIdentifier",
                    "Get-SPDscFarmProductsInfo",
                    "Get-SPDscFarmVersionInfo",
                    "Convert-SPDscADGroupIDToName",
                    "Convert-SPDscADGroupNameToID")

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module
#AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -prefix.
# DefaultCommandPrefix = ''

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PowerShell/SharePointDsc/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PowerShell/SharePointDsc'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = "
      * Changes to SharePointDsc
        * Added support for SharePoint 2019
        * Added CredSSP requirement to the Readme files
        * Added VSCode Support for running SharePoint 2019 unit tests
        * Removed the deprecated resources SPCreateFarm and SPJoinFarm (replaced
          in v2.0 by SPFarm)
      * SPBlobCacheSettings
        * Updated the Service Instance retrieval to be language independent
      * SPConfigWizard
        * Fixed check for Ensure=Absent in the Set method
      * SPInstallPrereqs
        * Added support for detecting updated installation of Microsoft Visual C++
          2015/2017 Redistributable (x64) for SharePoint 2016 and SharePoint 2019.
      * SPSearchContentSource
        * Added support for Business Content Source Type
      * SPSearchMetadataCategory
        * New resource added
      * SPSearchServiceApp
        * Updated resource to make sure the presence of the service app proxy is
          checked and created if it does not exist
      * SPSecurityTokenServiceConfig
        * The resource only tested for the Ensure parameter. Added more parameters
        * SPServiceAppSecurity
        * Added support for specifying array of access levels.
        * Changed implementation to use Grant-SPObjectSecurity with Replace switch
          instead of using a combination of Revoke-SPObjectSecurity and
          Grant-SPObjectSecurity
        * Added all supported access levels as available values.
        * Removed unknown access levels: Change Permissions, Write, and Read
      * SPUserProfileProperty
        * Removed obsolete parameters (MappingConnectionName, MappingPropertyName,
          MappingDirection) and introduced new parameter PropertyMappings
      * SPUserProfileServiceApp
        * Updated the check for successful creation of the service app to throw an
          error if this is not done correctly

      The following changes will break v2.x and earlier configurations that use these
      resources:

      * Implemented IsSingleInstance parameter to force that the resource can only
        be used once in a configuration for the following resources:
        * SPAntivirusSettings
        * SPConfigWizard
        * SPDiagnosticLoggingSettings
        * SPFarm
        * SPFarmAdministrators
        * SPInfoPathFormsServiceConfig
        * SPInstall
        * SPInstallPrereqs
        * SPIrmSettings
        * SPMinRoleCompliance
        * SPPasswordChangeSettings
        * SPProjectServerLicense
        * SPSecurityTokenServiceConfig
        * SPShellAdmin
      * Standardized Url/WebApplication parameter to default WebAppUrl parameter
        for the following resources:
        * SPDesignerSettings
        * SPFarmSolution
        * SPSelfServiceSiteCreation
        * SPWebAppBlockedFileTypes
        * SPWebAppClientCallableSettings
        * SPWebAppGeneralSettings
        * SPWebApplication
        * SPWebApplicationAppDomain
        * SPWebAppSiteUseAndDeletion
        * SPWebAppThrottlingSettings
        * SPWebAppWorkflowSettings
      * Introduced new mandatory parameters
        * SPSearchResultSource: Added option to create Result Sources at different scopes.
        * SPServiceAppSecurity: Changed parameter AccessLevel to AccessLevels in
          MSFT_SPServiceAppSecurityEntry to support array of access levels.
        * SPUserProfileProperty: New parameter PropertyMappings
      "
    } # End of PSData hashtable

} # End of PrivateData hashtable
}

