[ClassVersion("1.0.0.0"), FriendlyName("SPAppStoreSettings")]
class MSFT_SPAppStoreSettings : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("Specifies if App Purchases from the SharePoint Store are allowed")] Boolean AllowAppPurchases;
    [Write, Description("Specifies if App Purchases for Office applications are allowed")] Boolean AllowAppsForOffice;
};
