/*
**Description**

This resource is used to set the global antivirus settings for the local farm.
These settings will be used to control the behavior of an external anti-virus scanning tool that is able to integrate with SharePoint.
Note that this will not scan documents for viruses on it's own, an external tool still needs to be installed on the servers that integrates with SharePoint.

**Example**

    xSPHealthAnalyzerRuleState DisableDiskSpaceRule
    {
        Name = "Drives are at risk of running out of free space."
        Enabled = $true
        Scope   = "All Servers"
        Schedule = "Daily"
        FixAutomatically = $false
        InstallAcount = $InstallAccount
    }
*/

[ClassVersion("1.0.0.0"), FriendlyName("xSPHealthAnalyzerRuleState")]
class MSFT_xSPHealthAnalyzerRuleState : OMI_BaseResource
{
    [Key] String Name;
    [Required] Boolean Enabled;
    [Write, ValueMap{"All Servers", "Any Server"}, Values{"All Servers", "Any Server"}] String Scope;
    [Write, ValueMap{"Hourly","Daily","Weekly","Monthly","OnDemandOnly"}, Values{"Hourly","Daily","Weekly","Monthly","OnDemandOnly"}] String Schedule;
    [Write] Boolean FixAutomatically;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

