/*
**Description**

This resource is used to control settings that relate to the automatic changing of passwords for managed accounts (where they opt-in to be managed by SharePoint).
These settings can be manually controlled through central administration, or configured in this resource.
The settings relate to email notifications of when passwords are reset, as well as behavior when a reset occurs such as a time out and number of retries.

**Example**

    xSPPasswordChangeSettings ManagedAccountPasswordResetSettings
    {  
        MailAddress                   = "sharepoint@contoso.com"
        DaysBeforeExpiry              = "14"
        PasswordChangeWaitTimeSeconds = "60"
        NumberOfRetries               = "3"
        PsDscRunAsCredential          = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPPasswordChangeSettings")]
class MSFT_xSPPasswordChangeSettings  : OMI_BaseResource
{
    [key] string MailAddress;
    [Write] Uint32 DaysBeforeExpiry;
    [Write] Uint32 PasswordChangeWaitTimeSeconds;
    [Write] Uint32 NumberOfRetries;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
