[ClassVersion("1.0.0.0"), FriendlyName("xSPPasswordChangeSettings")]
class MSFT_xSPPasswordChangeSettings  : OMI_BaseResource
{
    [key] string MailAddress;
    [Write] Uint32 DaysBeforeExpiry;
    [Write] Uint32 PasswordChangeWaitTimeSeconds;
    [Write] Uint32 NumberOfRetries;
	[Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
