[ClassVersion("1.0.0.0"), FriendlyName("SPTrustedSecurityTokenIssuer")]
class MSFT_SPTrustedSecurityTokenIssuer : OMI_BaseResource
{
    [Key, Description("Name of the SPTrustedSecurityTokenIssuer")] String Name;
    [Write, Description("Description of the SPTrustedSecurityTokenIssuer")] String Description;
    [Write, Description("The security principal identifier of the security token issuer")] String RegisteredIssuerNameIdentifier;
    [Write, Description("The realm of the security token issuer")] String RegisteredIssuerNameRealm;
    [Write, Description("Specify the thumbprint of the signing certificate, which must be located in certificate store LocalMachine\\My")] String SigningCertificateThumbprint;
    [Write, Description("Specify the file path to the signing certificate if it is not stored in the local certificate store already")] String SigningCertificateFilePath;
    [Write, Description("URL that SharePoint will reach to download the JSON metadata file of the issuer")] String MetadataEndPoint;
    [Write, Description("Specifies whether the trust is established with a self-issuer partner app")] Boolean IsTrustBroker;
    [Write, Description("Present if the SPTrustedSecurityTokenIssuer should be created, or Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
};
