[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationHappyHour
{
    [write] uint32 Hour;
    [write] uint32 Minute;
    [write] uint32 Duration;

};
/*
**Description**

This resource is responsible for setting web application settings that are found under the "resource throttling" screen in central admin.
The web application is specified through the URL property, and then any combination of settings can be applied.
Any settings not included will be left as the default (or whatever they have been manually changed to within SharePoint).
Happy hour is the setting used to control the window where threshold do not apply throughout the day.
You can specify the start time of this window as well as how many hours it will last.

**Example**

    xSPWebAppThrottlingSettings PrimaryWebAppThrottlingSettings
    {
        Url                      = "Shttp://exmaple.contoso.local"
        ListViewThreshold        = 5000
		AllowObjectModelOverride = $false
		HappyHourEnabled         = $true
		HappyHour                = MSFT_xSPWebApplicationHappyHour {
		    Hour     = 3
			Minute   = 0
			Duration = 1
		}
        PsDscRunAsCredential     = $InstallAccount
    }
*/
[ClassVersion("1.0.0"), FriendlyName("xSPWebAppThrottlingSettings")]
Class MSFT_xSPWebAppThrottlingSettings
{
    [Key] string Url;
    [write] uint32 ListViewThreshold;
    [write] boolean AllowObjectModelOverride; 
    [write] uint32 AdminThreshold;
    [write] uint32 ListViewLookupThreshold;
    [write] boolean HappyHourEnabled;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationHappyHour")] string HappyHour;
    [write] uint32 UniquePermissionThreshold;
    [write] boolean RequestThrottling;
    [write] boolean ChangeLogEnabled;
    [write] uint32 ChangeLogExpiryDays;
    [write] boolean EventHandlersEnabled;
    [Write, EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};