[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationHappyHour
{
    [write] uint32 Hour;
    [write] uint32 Minute;
    [write] uint32 Duration;

};
/*
**Description**

This resource is responsible for setting web application settings that are found under the "resource throttling" screen in central admin.
The web application is specified through the URL property, and then any combination of settings can be applied.
Any settings not included will be left as the default (or whatever they have been manually changed to within SharePoint).
Happy hour is the setting used to control the window where threshold do not apply throughout the day.
You can specify the start time of this window as well as how many hours it will last.

**Example**

    xSPWebAppThrottlingSettings PrimaryWebAppThrottlingSettings
    {
        Url                      = "Shttp://exmaple.contoso.local"
        ListViewThreshold        = 5000
        AllowObjectModelOverride = $false
        HappyHourEnabled         = $true
        HappyHour                = MSFT_xSPWebApplicationHappyHour {
            Hour     = 3
            Minute   = 0
            Duration = 1
        }
        PsDscRunAsCredential     = $InstallAccount
    }
*/
[ClassVersion("1.0.0"), FriendlyName("xSPWebAppThrottlingSettings")]
Class MSFT_xSPWebAppThrottlingSettings : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string Url;
    [Write, Description("What should the list view threshold for this site be set to")] uint32 ListViewThreshold;
    [Write, Description("Should object model code be able to be override the list view threshold")] boolean AllowObjectModelOverride; 
    [Write, Description("What is the list view threshold for site administrators")] uint32 AdminThreshold;
    [Write, Description("What is the maximum number of lookup fields in a single list view")] uint32 ListViewLookupThreshold;
    [Write, Description("Should the happy hour window be enabled for this web app")] boolean HappyHourEnabled;
    [Write, Description("The time window for happy hour"), EmbeddedInstance("MSFT_xSPWebApplicationHappyHour")] string HappyHour;
    [Write, Description("What is the limit for unique permissions on a single object in this web app")] uint32 UniquePermissionThreshold;
    [Write, Description("Is request throttling enabled on this web app")] boolean RequestThrottling;
    [Write, Description("Is the change log enabled for this web app")] boolean ChangeLogEnabled;
    [Write, Description("How many days does the change log store data for")] uint32 ChangeLogExpiryDays;
    [Write, Description("Are event handlers enabled in the web application")] boolean EventHandlersEnabled;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};