/*
**Description**

This resource is responsible for provisioning the search service application. 
The current version lets you specify the database name and server, as well as the application pool.
If the application pool is changed the DSC resource will set it back as per what is set in the resource.
The database name parameter is used as the prefix for all search databases (so you will end up with one for the admin database which matches the name, and then "_analyticsreportingstore", "_crawlstore" and "_linkstore" databases as well).

**Example**

    xSPSearchServiceApp SearchServiceApp
    {  
        Name                  = "Search Service Application"
        DatabaseName          = "SP_Search"
        ApplicationPool       = "SharePoint Service Applications"
        PsDscRunAsCredential  = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("xSPSearchServiceApp")]
class MSFT_xSPSearchServiceApp : OMI_BaseResource
{
    [Key] string Name;
    [Required] string ApplicationPool;
    [Write] string DatabaseName;
    [Write] string DatabaseServer;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

