
/*
**Description**

This resource will create a property in a user profile service application. 
It creates, update or delete a property using the parameters that are passed in to it .

The parameter DisplayOrder is absolute. ie.: If you want it to be placed as the 5th field of section Bla, which has propertyName value of 5000 then your DisplayOrder needs to be 5005
If no DisplayOrder is added then SharePoint adds it as the last property of section X.

Length is only relevant if Field type is "String".

This DSC resource doesn't currently supports metadata properties

-- needs to add support to
   - linking to MMS terms
   - indexed properties
**Example**
xSPUserProfileProperty WorkEmailProperty
{
    Name = "WorkEmail2"
    UserProfileServiceAppName = "User Profile Service Application"
    DisplayName = "Work Email"
    Type = "Email"
    Description = "" #implementation isn't using it yet
    PolicySetting = "Required"
    PrivacySetting = "Everyone"
    MappingConnectionName = "contoso.com"
    MappingPropertyName = "mail"
    MappingDirection = "Import"
    Length = 10
    DisplayOrder =25 #relative to the section 
    IsEventLog =$false
    IsVisibleOnEditor=$true
    IsVisibleOnViewer = $true
    IsUserEditable = $true
    IsAlias = $false #: used to edit "Alias" of the property value under Search Settings.
    IsSearchable = $false # e: used to edit “Indexed” of the property value again under Search Settings.
    TermStore = ""
    TermGroup = ""
    TermSet = "" 
    UserOverridePrivacy = $false
}

*/


[ClassVersion("1.0.0.0"), FriendlyName("xSPUserProfileProperty")]
class MSFT_xSPUserProfileProperty : OMI_BaseResource
{
    [Key] string Name 
    [ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [required] string UserProfileServiceAppName 
    [required] string DisplayName 
    [Required, [ValueMap{"BigInteger", "Binary", "Boolean", "Date", "DateNoYear", "DateTime", "Email", "Float", "Guid", "HTML", "Integer", "Person", "String",  "StringMultiValue", "TimeZone", "URL"}, Values{"BigInteger", "Binary", "Boolean", "Date", "DateNoYear", "DateTime", "Email", "Float", "Guid", "HTML", "Integer", "Person", "String",  "StringMultiValue", "TimeZone", "URL"}] ] string Type
    [write] string Description 
    [ValueMap{"Mandatory", "Optin","Optout", "Disabled"}, Values{"Mandatory", "Optin","Optout", "Disabled"}] string PolicySetting;
    [ValueMap{"Public", "Contacts", "Organization", "Manager", "Private"}, Values{"Public", "Contacts", "Organization", "Manager", "Private"}] string PrivacySetting ;
    [write] string MappingConnectionName 
    [write] string MappingPropertyName 
    [write] string MappingDirection 
    [write] uint32 Length 
    [write] uint32 DisplayOrder
    [write] boolean IsEventLog 
    [write] boolean IsVisibleOnEditor
    [write] boolean IsVisibleOnViewer
    [write] boolean IsUserEditable 
    [write] boolean IsAlias
    [write] boolean IsSearchable
    [write] boolean UserOverridePrivacy 
    [write] string TermStore 
    [write] string TermSetGroup
    [write] string TermSet
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};



