/*
**Description**

This resource is used to set the "super user" and "super reader" cache accounts for the specified web application object (as described in the TechNet article [Configure object cache user accounts in SharePoint Server 2013](https://technet.microsoft.com/en-us/library/ff758656.aspx)).

**Example**

    SPCacheAccounts SetCacheAccounts
    {
        WebAppUrl            = "http://sharepoint.contoso.com"
        SuperUserAlias       = "DEMO\svcSPSuperUser"
        SuperReaderAlias     = "DEMO\svcSPReader"
        PsDscRunAsCredential = $InstallAccount
    }
*/
[ClassVersion("1.0.0.0"), FriendlyName("SPCacheAccounts")]
class MSFT_SPCacheAccounts : OMI_BaseResource
{
    [Key, Description("The URL of the web application to set the accounts for")] string WebAppUrl;
    [Required, Description("The account name for the super user")] string SuperUserAlias;
    [Required, Description("The account name for the super reader")] string SuperReaderAlias;
    [Write, Description("Should the web app policy be set for these accounts?")] boolean SetWebAppPolicy;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

