[ClassVersion("1.0.0.0")]
Class MSFT_SPWebAppAuthenticationMode
{
    [Required, Description("Specifies the used authentication method"), ValueMap{"Classic","WindowsAuthentication","FBA","Federated"}, Values{"Classic","WindowsAuthentication","FBA","Federated"}] String AuthenticationMethod;
    [Write, Description("Method of Windows authentication (NTLM or Kerberos, only for Windows Authentication)"), ValueMap{"NTLM","Kerberos"}, Values{"NTLM","Kerberos"}] String WindowsAuthMethod;
    [Write, Description("Use Basic Authentication (only for Windows Authentication)")] Boolean UseBasicAuth;
    [Write, Description("Name of the TrustedIdentityTokenIssuer (only for Federated)")] String AuthenticationProvider;
    [Write, Description("Name of Membership Provider (only for FBA)")] String MembershipProvider;
    [Write, Description("Name of the Role Manager (only for FBA)")] String RoleProvider;
};
[ClassVersion("1.0.0.0")]
Class MSFT_SPWebAppZoneSettings
{
    [Write, Description("Use Anonymous Authentication for the zone")] Boolean AnonymousAuthentication;
    [Write, Description("Specifies the URL to the custom signin page for the zone")] String CustomSignInPage;
    [Write, Description("Enable the Client Integration features for the zone")] Boolean EnableClientIntegration;
    [Write, Description("Enable the Require Use Remote Interfaces for the zone")] Boolean RequireUseRemoteInterfaces;
};
[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppAuthentication")]
class MSFT_SPWebAppAuthentication : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("Specifies the authentication for the Default zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Default[];
    [Write, Description("Specifies the authentication for the Intranet zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Intranet[];
    [Write, Description("Specifies the authentication for the Internet zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Internet[];
    [Write, Description("Specifies the authentication for the Extranet zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Extranet[];
    [Write, Description("Specifies the authentication for the Custom zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Custom[];
    [Write, Description("Specifies the zone settings for the Default zone."), EmbeddedInstance("MSFT_SPWebAppZoneSettings")] string DefaultSettings;
    [Write, Description("Specifies the zone settings for the Intranet zone."), EmbeddedInstance("MSFT_SPWebAppZoneSettings")] string IntranetSettings;
    [Write, Description("Specifies the zone settings for the Internet zone."), EmbeddedInstance("MSFT_SPWebAppZoneSettings")] string InternetSettings;
    [Write, Description("Specifies the zone settings for the Extranet zone."), EmbeddedInstance("MSFT_SPWebAppZoneSettings")] string ExtranetSettings;
    [Write, Description("Specifies the zone settings for the Custom zone."), EmbeddedInstance("MSFT_SPWebAppZoneSettings")] string CustomSettings;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};
